### ISSUE TITLE
Jenkinx X is not able to login in minishift. 

### ISSUE THREAD

**Issue by david-romero** [jenkins-x/jx#1034]
I'm creating a minishift cluster and when I executes 'jx create cluster minishift', the commands returns the following error:

 
![imagen](https://user-images.githubusercontent.com/8822102/41401801-0f554342-6fc1-11e8-97c5-e3948d4c2744.png)

I've executed above login command ( oc login -u system:admin ) in minishift and it doesn't works.

![imagen](https://user-images.githubusercontent.com/8822102/41401951-5f03d69c-6fc1-11e8-853d-ea69b61da635.png)

However, if I executes 'oc login -u system -p admin', it works great
 
![imagen](https://user-images.githubusercontent.com/8822102/41402057-9b99576c-6fc1-11e8-9753-514f8fdc04f0.png)

Could be a bug?

I have been researching in the repository and I found the following code:

https://github.com/jenkins-x/jx/search?q=oc+login+-u+system%3Aadmin&unscoped_q=oc+login+-u+system%3Aadmin

Jenkins x version: (v1.2.127)  https://github.com/jenkins-x/jx/releases/download/v1.2.127/jx-linux-amd64.tar.gz
Minishift version: minishift v1.18.0+756b128

**Comment by migangqui** [comment]
https://github.com/jenkins-x/jx/pull/1035

**Comment by migangqui** [comment]
PR to solve https://github.com/jenkins-x/jx/pull/1035

**Comment by david-romero** [comment]
Fixed by @migangqui and merged by @jstrachan 
https://github.com/jenkins-x/jx/commit/8f95dcf5a15afdc04e2865e8042a33f2cd3a597d

Thanks guys! :smiley:

**Comment by magnum99** [comment]
Even after this fix I was not able to run jx create cluster minishift (on a clean minishift i.e. after running minishift delete --clear-cache). It is still failing because od insecure tls connection and because the system user does not have enough permissions to create cluster namespace.

jx 1.2.133
minishift v1.18.0+756b128

**Comment by david-romero** [comment]
You're right! I've tested the fix only one time and the problem is not fixed yet. I hope your PR can fix the issue. 

One question @magnum99 or @jstrachan  , How can I package jx on my laptop? 
@migangqui and I want to try on our laptop before submiting a new PR.

Thank you very much for your feedback!

**Comment by magnum99** [comment]
@david-romero you can run either go run 
cmd/jx/jx.go create cluster minishift 
or use the make build command (which will produce jx binary)

**Comment by david-romero** [comment]
Thank you @magnum99 !! Now, I'm able to debug Jenkins X hahaha

**Comment by migangqui** [comment]
I set up with command **go run cmd/jx/jx.go create cluster minishift** in my local.

Jx 1.2.133
Minishift version: v1.18.0+756b128

**Comment by magnum99** [comment]
so maybe if you agree that it works correctly right now, this ticket could be closed?
