### ISSUE TITLE
jx sync doesn't sync any code on minikube

### ISSUE THREAD

**Issue by johnmcollier** [jenkins-x/jx#1694]
### Summary 
I set up a Jenkins-X install on Minikube (see configuration below). I created a sample go project using `jx create quickstart`, then started up a `jx sync` process in that folder and then ran `jx create devpod --sync`. The devpod came up fine and I could exec into it, however the code was nowhere to be found on the pod. Additionally, the output of the sync process looks like so:

```
Johns-MacBook-Pro-3:gotester1 johncollier$ jx sync
ksync is already available on your PATH at /Users/johncollier/.jx/bin/ksync
Looks like 'ksync watch' is not running: Command failed 'ksync get': time="2018-09-15T23:29:44-04:00" level=fatal msg="Having problems querying status. Are you running watch?" exit status 1

Started the ksync watch
INFO[0000] listening                                     bind=127.0.0.1 port=40322
INFO[0002] syncthing listening                           port=8384 syncthing=localhost
```

This output never changes, even if I make local changes to the project. Am I missing something here? The docs [here](https://jenkins-x.io/developing/devpods/), make it seem like that is all that is required. This issue is possibly related to https://github.com/jenkins-x/jx/issues/1551, but was closed by the author shortly after opening it.

### Steps to reproduce the behavior
1) Set up a Minikube cluster running Jenkins-X
2) Create a Go quickstart project
3) Run `jx sync` and create a devpod for the project
4) See if the project code is synced over to the devpod

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.272
jenkins x platform 0.0.2397
kubernetes cluster v1.10.0
kubectl            v1.9.4
helm client        v2.10.0+g9ad53aa
helm server        v2.10.0+g9ad53aa
git                git version 2.15.2 (Apple Git-101.1)
```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?

Minikube cluster with 8gb memory, 8cpu, and 200gb storage. 

### Expected behavior
The code syncs.
### Actual behavior
The code never syncs.

**Comment by ccojocar** [comment]
@johnmcollier Please could you try with the latest version of jx CLI? We fixed recently a few things. Does the `create devpods` command opens a shell into the pod?

Also sometimes `ksync` hangs. You can kill all ksync processes and run again `jx sync`.

**Comment by johnmcollier** [comment]
@ccojocar Thanks, updating the jx cli seems to have resolved my issue.

**Comment by johnmcollier** [comment]
Hmm, nevermind. I'm still seeing it on the latest cli. I must've forgotten the `--sync` flag earlier :(

```
Johns-MacBook-Pro-3:microprofile-x johncollier$ jx sync
ksync is already available on your PATH at /Users/johncollier/.jx/bin/ksync
Looks like 'ksync watch' is not running: Command failed 'ksync get': time="2018-09-17T21:10:18-04:00" level=fatal msg="Having problems querying status. Are you running watch?" exit status 1

Started the ksync watch
INFO[0000] listening                                     bind=127.0.0.1 port=40322
INFO[0002] syncthing listening                           port=8384 syncthing=localhost
```
