### ISSUE TITLE
The jenkins-x-gc-activities pods start to fail and bring down Jenkins (still present)

### ISSUE THREAD

**Issue by g-foster** [jenkins-x/jx#2218]
I am still seeing this issue #1705; my description is as per #1705 and I think this should be closed and that issue reopened, but for context:

1. Create a cluster in EKS with default environments.
2. Let it run for a few hours and the failing pods start to build up.

For example, on a default install (no imported project) of JX into EKS, after two days I have just deleted over 400 of these

jenkins-x-gcactivities-1541615400-8s7sd 0/1 Error 0 7m
jenkins-x-gcactivities-1541615400-fj2tb 0/1 Error 0 3m
jenkins-x-gcactivities-1541615400-lpkxt 0/1 Error 0 5m

My versions:

Running in namespace: jx
Jenkins X Version:
Using helmBinary helm with feature flag: none
NAME VERSION
jx 1.3.535
jenkins x platform 0.0.2859
Kubernetes cluster v1.10.3-eks
kubectl v1.12.2
helm client v2.11.0+g2e55dbe
helm server v2.11.0+g2e55dbe
git git version 2.17.2 (Apple Git-113)

but I assumed I would have the fix/workaround from #1705.

**Comment by ranginuitrot** [comment]
Can confirm it's happening to me too.

**Comment by rawlingsj** [comment]
Can you paste the logs from one of the failed pods please?

**Comment by ranginuitrot** [comment]
Will do next time it happens. I reinstalled Jenkins X right after posting.

**Comment by ranginuitrot** [comment]
Here's one of the pod's logs:

```
Error loading team settings. environments.jenkins.io is forbidden: User "system:serviceaccount:jx:jenkins-x-gcactivities" cannot list environments.jenkins.io in the namespace "jx"
Error loading team settings. environments.jenkins.io is forbidden: User "system:serviceaccount:jx:jenkins-x-gcactivities" cannot list environments.jenkins.io in the namespace "jx"
plugins.jenkins.io is forbidden: User "system:serviceaccount:jx:jenkins-x-gcactivities" cannot list plugins.jenkins.io in the namespace "jx"
 To be able to connect to the Jenkins server we need a username and API Token
 error: EOF
? Jenkins user name: (admin) 7
```

`kc describe pod jenkins-x-gcactivities-1544562000-29d6v`:
```
Name:           jenkins-x-gcactivities-1544562000-29d6v
Namespace:      jx
Node:           ip-10-1-9-10.ec2.internal/10.1.9.10
Start Time:     Tue, 11 Dec 2018 15:02:45 -0600
Labels:         app=gcactivities
                controller-uid=badd0f1d-fd87-11e8-b690-0a0697b453e4
                job-name=jenkins-x-gcactivities-1544562000
                release=jenkins-x
Annotations:    <none>
Status:         Failed
IP:             10.1.8.255
Controlled By:  Job/jenkins-x-gcactivities-1544562000
Containers:
  gcactivities:
    Container ID:  docker://3802db8b4c0428316e1462b5a4b769725b71a8ba9a91a00e764fb0157bbf2874
    Image:         jenkinsxio/jx:1.3.639
    Image ID:      docker-pullable://jenkinsxio/jx@sha256:b6ad86b6b3b54c45f358417cfcc8895e1710d3759105c0b92228db362e07510e
    Port:          <none>
    Host Port:     <none>
    Command:
      jx
    Args:
      gc
      activities
    State:          Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Tue, 11 Dec 2018 15:02:45 -0600
      Finished:     Tue, 11 Dec 2018 15:02:45 -0600
    Ready:          False
    Restart Count:  0
    Environment:
      cheese:  wine
      foo:     bar
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from jenkins-x-gcactivities-token-xlqhs (ro)
Conditions:
  Type           Status
  Initialized    True 
  Ready          False 
  PodScheduled   True 
Volumes:
  jenkins-x-gcactivities-token-xlqhs:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  jenkins-x-gcactivities-token-xlqhs
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type    Reason                 Age   From                                Message
  ----    ------                 ----  ----                                -------
  Normal  Scheduled              10m   default-scheduler                   Successfully assigned jenkins-x-gcactivities-1544562000-29d6v to ip-10-1-9-10.ec2.internal
  Normal  SuccessfulMountVolume  10m   kubelet, ip-10-1-9-10.ec2.internal  MountVolume.SetUp succeeded for volume "jenkins-x-gcactivities-token-xlqhs"
  Normal  Pulled                 10m   kubelet, ip-10-1-9-10.ec2.internal  Container image "jenkinsxio/jx:1.3.639" already present on machine
  Normal  Created                10m   kubelet, ip-10-1-9-10.ec2.internal  Created container
  Normal  Started                10m   kubelet, ip-10-1-9-10.ec2.internal  Started container
```

**Comment by ranginuitrot** [comment]
```
NAME               VERSION
jx                 1.3.651
jenkins x platform 0.0.3036
Kubernetes cluster v1.10.11-eks
kubectl            v1.13.0
helm client        v2.12.0+gd325d2a
helm server        v2.12.0+gd325d2a
git                git version 2.17.2 (Apple Git-113)
Operating System   Mac OS X 10.14.1 build 18B75
```

**Comment by sboardwell** [comment]
Can confirm this is also happening on our GKE cluster. Symptoms identical to @rust84 and @ranginuitrot. 

```
$ jx version
NAME               VERSION
jx                 1.3.640
jenkins x platform 0.0.3036
Kubernetes cluster v1.10.9-gke.5
kubectl            v1.11.3
helm client        v2.11.0+g2e55dbe
helm server        v2.11.0+g2e55dbe
git                git version 2.18.0
Operating System   Mac OS X 10.13.6 build 17G4015
```

Should the jenkins-x-gc-activities be asking for those resources in the first place, or is something wrong in our setup? It seems that the `gcactivities` should not have these permissions in the first place looking at `values.yaml` here: https://github.com/jenkins-x/jenkins-x-platform/blob/master/values.yaml#L63

The `controllerbuild` on the other hand has them: https://github.com/jenkins-x/jenkins-x-platform/blob/master/values.yaml#L313

Are the permissions added at another point in time? Perhaps when adding an environment (we installed Jenkins X with the `--no-default-environments` option).

The workaround of adding cluster-admin to the service account would work but I would much prefer knowing what the problem is.

**Comment by thienlh** [comment]
Can confirm this is also happening on our EKS cluster.

```
NAME               VERSION
jx                 1.3.661
jenkins x platform 0.0.3036
Kubernetes cluster v1.10.11-eks
kubectl            v1.13.1
helm client        v2.12.0+gd325d2a
helm server        v2.12.0+gd325d2a
git                git version 2.20.1
Operating System   Mac OS X 10.14.2 build 18C54
```

**Comment by sboardwell** [comment]
Adding @pmuir to this as he mentioned in the jenkins-x-user Slack channel that 

> The permissions errors in that log statement are misleading, they don't cause the code to fail
> I'll get them removed

Any idea why this may be happening @pmuir?

One idea I have is that, through switching jx contexts (I had a minikube installation and a GKE installation running), the values in the yaml files created during installation on one cluster were somehow used/included/replaced the values in the other installation.
```$ ls -1 ~/.jx/*.yaml
/Users/sboardwell/.jx/adminSecrets.yaml
/Users/sboardwell/.jx/chartmuseumAuth.yaml
/Users/sboardwell/.jx/gitAuth.yaml
/Users/sboardwell/.jx/jenkinsAuth.yaml```

**Comment by pmuir** [comment]
@ccojocar is this becaue of removing old secrets?

**Comment by pmuir** [comment]
Actually no, this looks like an issue in the gc /cc @jstrachan

**Comment by sboardwell** [comment]
Hi @jstrachan, I used one of the failing pods to recreate a test pod and then used `kubectl exec -it .... bash`. Running `jx gc activities` indeed asked for credentials (and I can confirm, that the permissions log output has no meaning - @pmuir).

I'm not sure what is expected here, but here is what I found it:
* on initial log in as root, there is no `/root/.jx/jenkinsAuth.yaml` present.
* jx then asks for authentication
* using username admin and the respective api token did not work
   * however, we have installed and configured the keycloak plugin so perhaps the "local" admin user is no longer applicable
   * testing with my own username and my own api key worked (needed to delete the `jenkinsAuth.yaml` first). I could have also just edited the file I guess.

So:
* is the `/root/.jx/jenkinsAuth.yaml` supposed to be there when the jenkins-x-gcactivities pod is created?
* re: local admin vs keycloak. how do we best change the jenkins authentication values? 
   * the jenkinsAuth.yaml is found in the jx-install-config and the password in a number of other secrets?
   * can we change the admin users "username" to something other than 'admin'? The jenkins secret has the parameter `jenkins-admin-user: "true"` and `jenkins-admin-password` but no `jenkins-admin-username`

Let me know if I can supply any more information, and thanks for all the cool work.

**Comment by sboardwell** [comment]
@jstrachan - I don't think this issue has been fixed by just adding the missing roles. The missing roles  just removed ```
Error loading team settings. environments.jenkins.io is forbidden: User "system:serviceaccount:jx:jenkins-x-gcactivities" cannot list environments.jenkins.io in the namespace "jx"
Error loading team settings. environments.jenkins.io is forbidden: User "system:serviceaccount:jx:jenkins-x-gcactivities" cannot list environments.jenkins.io in the namespace "jx"
plugins.jenkins.io is forbidden: User "system:serviceaccount:jx:jenkins-x-gcactivities" cannot list plugins.jenkins.io in the namespace "jx"
``` 
from the logs. The pods are still failing because there is no authentication method.

**Comment by jstrachan** [comment]
OK I think those RBAC issues are fixed - am just waiting to see if I get any failures.

Though I'm still not sure why you are getting errors about the Jenkins API Token not being present. You are using Static Jenkins masters right - you're not using Prow / Serverless jenkins?

**Comment by jstrachan** [comment]
btw version `0.0.2859` is pretty old - we just released the RBAC fix in `0.0.3086`

**Comment by sboardwell** [comment]
Yes, I have ported your RBAC fixes and can confirm the log "forbidden" messages are gone. However, the pods are still failing as the Jenkins API token is missing. Where should it be? and how should it get there? I can see anything in the k8s cron job or job template.

**Comment by sboardwell** [comment]
Btw, I'm seeing this on `jenkins-x-platform-0.0.3078`

**Comment by sboardwell** [comment]
> You are using Static Jenkins masters
yes, sorry, I'm using a static master

**Comment by jstrachan** [comment]
the API token should be created for you when you first import a project into Jenkins X - have you done that yet - do you have any projects? e.g. does `jx get pipeline` return anything?

**Comment by jstrachan** [comment]
usually when using the static Jenkins master the api token has to be setup to be able to create the Staging and Production environments

**Comment by sboardwell** [comment]
No, no projects yet. I created a test pipeline job by hand. Let me check to see if it works.

**Comment by jstrachan** [comment]
I wonder if you are experiencing issues of an older cluster being upgrading not having the necessary Jenkins secret? e.g. if you `rm ~/.jx/jenkinsAuth.yaml` and then create/import a project it should create the necessary Jenkins secret?

**Comment by jstrachan** [comment]
usually the initial install creates the Jenkins API token secret as it sets up CI/CD for the Environments

**Comment by sboardwell** [comment]
Yes the `jenkins` secret is there, complete with api token, etc.

**Comment by sboardwell** [comment]
```
$ k get secrets jenkins -o yaml | ksd
apiVersion: v1
data:
  jenkins-admin-api-token: {REDACTED}
  jenkins-admin-password: {REDACTED}
  jenkins-admin-user: admin
  jenkins-bearer-token: ""
kind: Secret
metadata:
  creationTimestamp: "2018-12-16T19:59:23Z"
  labels:
    app: jenkins
    chart: jenkins-0.10.31
    heritage: Tiller
    release: jenkins-x
  name: jenkins
  namespace: jx
  resourceVersion: "14531"
  selfLink: /api/v1/namespaces/jx/secrets/jenkins
  uid: 15a140f3-016d-11e9-8c5f-1e557db74be1
type: Opaque
```

**Comment by ranginuitrot** [comment]
@jstrachan can confirm this issue still happens after a completely clean install.

**Comment by rawlingsj** [comment]
oops - bad copy paste of issues sorry

**Comment by sboardwell** [comment]
Just confirming this has fixed my problem. Great work. Thanks a lot!

**Comment by anilkumarpasupuleti** [comment]
@sboardwell , how did you solve your problem. i have similar kind of issue?. my pods status shows like this? 
jenkins-x-gcactivities-1574078400-227nt      0/1     Error               0          112m
jenkins-x-gcactivities-1574078400-24bs6      0/1     Error               0          116m
jenkins-x-gcactivities-1574078400-24kf4      0/1     Error               0          89m

and the logs of the pod shows as below
 kubectl logs jenkins-x-gcactivities-1574080200-zzld9
error: Could not find any user auths for jenkins server http://jenkins.xxx.xx.xx.xx.xx.nip.io.io has server URLs
Thanks

**Comment by sboardwell** [comment]
@anilkumarpasupuleti - I can't remember exactly. I ended up starting up a jenkins-x-gcactivities pod of my own to debug. I think it had something to do with the initial installation values having changed or something.

**Comment by gswallow** [comment]
I just hit this issue.  If I follow @sboardwell's comment and touch an empty /root/.jx/jenkinsAuth.yaml file, then `jx gc activities` works just fine.  Maybe too well.

Image:         gcr.io/jenkinsxio/builder-jx:2.0.1063-390.
