### ISSUE TITLE
jx create cluster eks fails with 'ERROR: error installing helm: Unable to download'

### ISSUE THREAD

**Issue by pguimaraes** [jenkins-x/jx#6110]
### Summary

Jenkins X version 2.0.979 cannot download helm.

### Steps to reproduce the behavior

jx --version
2.0.979

jx create cluster eks --skip-installation=true --install-dependencies=true --eksctl-log-level=4 --cluster-name="XXX" --region="us-east-1" --zones="us-east-1a,us-east-1b" --node-type="m5.large" --nodes=2 --nodes-min=2 --nodes-max=4 --tags="CreatedBy=JenkinsX" --username="XXX" --verbose=true --batch-mode=true

### Expected behavior

Successful cluster creation.

### Actual behavior

DEBUG: Dependencies to be installed: eksctl, aws-iam-authenticator
Installing eksctl
Downloading https://github.com/weaveworks/eksctl/releases/download/latest_release/eksctl_Linux_amd64.tar.gz to /home/XXX/.jx/bin/eksctl.tar.gz...
Downloaded /home/XXX/.jx/bin/eksctl.tar.gz
Installing aws-iam-authenticator
Downloading https://amazon-eks.s3-us-west-2.amazonaws.com/1.12.7/2019-03-27/bin/linux/amd64/aws-iam-authenticator to /home/XXX/.jx/bin/aws-iam-authenticator...
Downloaded /home/XXX/.jx/bin/aws-iam-authenticator
Installing kubectl
Downloading https://storage.googleapis.com/kubernetes-release/release/v1.13.2/bin/linux/amd64/kubectl to /home/XXX/.jx/bin/kubectl...
Downloaded /home/XXX/.jx/bin/kubectl
Installing helm
Downloading https://storage.googleapis.com/kubernetes-helm/helm-v3.0.0-linux-amd64.tar.gz to /home/XXX/.jx/bin/helm.tgz...
ERROR: error installing helm: Unable to download file /home/XXX/.jx/bin/helm.tgz from https://storage.googleapis.com/kubernetes-helm/helm-v3.0.0-linux-amd64.tar.gz due to: download of https://storage.googleapis.com/kubernetes-helm/helm-v3.0.0-linux-amd64.tar.gz failed with return code 404

Please fix the error or install manually then try again

### Jx version

The output of `jx version` is:

```
$ jx version
error: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined
$
$ jx --version
2.0.979

```

### Jenkins type

- [ ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [X ] Classic Jenkins

### Kubernetes cluster

EKS cluster on AWS.

### Operating system / Environment

Ubuntu 18.04 LTS

**Comment by pguimaraes** [comment]
I created an EKS cluster on AWS using Jenkins X version 2.0.918 on October 28 and this installation successfully downloaded https://storage.googleapis.com/kubernetes-helm/helm-v2.15.1-linux-amd64.tar.gz.  However, I just tried to install a new cluster using Jenkins X version 2.0.918 (instead of version 2.0.979 listed above), and this time it attempted to download https://storage.googleapis.com/kubernetes-helm/helm-v3.0.0-linux-amd64.tar.gz, just like Jenkins X version 2.0.979 did above.

It looks like function GetLatestVersionFromGitHub in file pkg/util/downloads.go is attempting to get the latest version of Helm from GitHub, which recently changed to v3.0.0.  However, this version of Helm is not available at the same location as the previous version v2.16.1 was, as shown below:

% curl -I https://storage.googleapis.com/kubernetes-helm/helm-v2.15.1-linux-amd64.tar.gz
HTTP/1.1 200 OK
...
%
% curl -I https://storage.googleapis.com/kubernetes-helm/helm-v2.16.1-linux-amd64.tar.gz
HTTP/1.1 200 OK
...
%
% curl -I https://storage.googleapis.com/kubernetes-helm/helm-v3.0.0-rc.4-linux-amd64.tar.gz
HTTP/1.1 404 Not Found
...
% 
% curl -I https://storage.googleapis.com/kubernetes-helm/helm-v3.0.0-linux-amd64.tar.gz
HTTP/1.1 404 Not Found
...
%

**Comment by pguimaraes** [comment]
As indicated at https://helm.sh/blog/get-helm-sh/#where-are-we-now, Helm client downloads are now published to a different location, so Jenkins X needs to update the URL for downloading the Helm binaries from now on.

**Comment by deanesmith** [comment]
Hi @pguimaraes A fix was merged last week.  Should be all set.

**Comment by rajeshmandya** [comment]
Hi,

I'm currently running
jx --version
2.1.155

And still facing this below issue, when i run "jx boot":
{{{
Installing helm
Downloading https://get.helm.sh/helm-v2.17.0-windows-amd64.tar.gz to C:\Users\rmputtas\.jx\bin\helm.tgz...
error: error installing helm: Unable to download file C:\Users\rmputtas\.jx\bin\helm.tgz from https://get.helm.sh/helm-v2.17.0-windows-amd64.tar.gz due to: download of https://get.helm.sh/helm-v2.17.0-windows-amd64.tar.gz failed with return code 403
error: failed to interpret pipeline file jenkins-x.yml: failed to run 'sh -c jx step verify preinstall --provider-values-dir="kubeProviders"' command in directory 'workspace\source', output: ''
}}}

Could anyone help me to resolve this?

Thanks
