### ISSUE TITLE
`jx boot` STEP: verify-jenkins-x-environment failing. Returning `401` Unauthorized, Body

### ISSUE THREAD

**Issue by huytn12-test** [jenkins-x/jx#6523]
### Summary 
I'm `jx boot` command to install Jenkins X Serverless on existing GKE cluster with Bitbucke and the installation failed at verify-jenkins-x-environment step. A 401 is returned when attempting to create dev environment on Bitbucket.

### Steps to reproduce the behavior
1. Run `jx boot` command
2. Modify the jx-requirements.yml to use Bitbucketcloud
```
autoUpdate:
  enabled: false
  schedule: ""
bootConfigURL: https://github.com/jenkins-x/jenkins-x-boot-config.git
cluster:
  clusterName: jenkins-x
  devEnvApprovers:
  - shipops
  environmentGitOwner: USER
  gitKind: bitbucketcloud
  gitName: bs
  gitServer: https://bitbucket.org
  namespace: jx
  project: myProject-eng-core-infra
  provider: gke
  registry: gcr.io
  zone: us-west1-a
environments:
- ingress:
    domain: 35.197.54.122.nip.io
    externalDNS: false
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: false
  key: dev
- ingress:
    domain: ""
    externalDNS: false
    namespaceSubDomain: ""
    tls:
      email: ""
      enabled: false
      production: false
  key: staging
- ingress:
    domain: ""
    externalDNS: false
    namespaceSubDomain: ""
    tls:
      email: ""
      enabled: false
      production: false
  key: production
gitops: true
ingress:
  domain: 35.197.54.122.nip.io
  externalDNS: false
  namespaceSubDomain: -jx.
  tls:
    email: ""
    enabled: false
    production: false
kaniko: true
repository: nexus
secretStorage: local
storage:
  backup:
    enabled: false
    url: ""
  logs:
    enabled: false
    url: ""
  reports:
    enabled: false
    url: ""
  repository:
    enabled: false
    url: ""
vault: {}
velero:
  schedule: ""
  ttl: ""
versionStream:
  ref: v1.0.299
  url: https://github.com/jenkins-x/jenkins-x-versions.git
webhook: lighthouse
```

### Expected behavior
Pass the verify-jenkins-x-environment

### Actual behavior

> Validating git repository for dev environment at URL https://bitbucket.org/myProject/environment-jenkins-x-dev.git
error: handle dev environment repository: creating remote for dev environment environment-jenkins-x-dev: duplicating https://github.com/jenkins-x/jenkins-x-boot-config to shipwire/environment-jenkins-x-dev: getting repo for https://github.com/jenkins-x/jenkins-x-boot-config: Status: 401 Unauthorized, Body:
error: failed to interpret pipeline file jenkins-x.yml: failed to run '/bin/sh -c jx step verify env' command in directory '.', output: ''

### Jx version

The output of `jx version` is:
```
jx                 2.0.1123
Kubernetes cluster v1.13.11-gke.14
kubectl            v1.16.2
helm client        Client: v2.16.1+gbbdfe5e
git                2.20.1 (Apple Git-117)
Operating System   Mac OS X 10.14.6 build 18G95
```

```
COPY OUTPUT HERE
```

### Jenkins type

- [ x ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

I created GKE cluster with web GUI

**Comment by abayer** [comment]
Hrrrrrm - I made changes in this space in the last week, but am not seeing this error show up in tests with other non github.com providers (GHE, Gitlab, Bitbucket Server) - wonder if it's something specific to Bitbucket Cloud. Another possibility is that you somehow have invalid GitHub creds in a secret in your cluster? No, probably not that. I'm not sure when I'll have a chance to reproduce this, but will do my best.

fwiw, I don't believe Lighthouse officially supports (even in preview form, like Gitlab/GHE/Bitbucket Server currently) Bitbucket Cloud.

**Comment by abayer** [comment]
At the very least, I know we're not testing Bitbucket Cloud with boot/gitops/Lighthouse.

**Comment by abayer** [comment]
Could you try this again with the latest jx binary? I believe this has been fixed.

**Comment by huytn12-test** [comment]
@abayer Sorry for the delayed response. I tried it and it worked great. Thanks for fixing the issues.

**Comment by majuansari** [comment]
@huytn12-test  @abayer   You did anything specific to sort out the issue? I am still facing the issue with bitbucket ?

Using the same configuration  @huytn12-test  mentioned

**Comment by huytn1219** [comment]
@majuansari No I didn't. what I remembered was I updated `jx` binary and then removed the `jx-requirements.yml` and ran the `jx boot` command again and the issue was disaapear.
